### ISSUE TITLE
Error happens read  No handlers could be found for logger "werkzeug"

### ISSUE THREAD

**Issue by ElizabethDuo** [MorvanZhou/pytorch-A3C#4]
Hi Marvan,
  I am trying to implement  A3C in another simulator based on your continuous and multiprocess A3C algorithms.
  However errors below showed up when running it

> No handlers could be found for logger "werkzeug"
  
and after press ctrl+c it showed

> Traceback (most recent call last):
  File "continuous_A3C.py", line 147, in <module>
    r = res_queue.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/usr/local/lib/python2.7/dist-packages/torch/multiprocessing/queue.py", line 21, in recv
    buf = self.recv_bytes()
KeyboardInterrupt
Process w0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process w1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "continuous_A3C.py", line 113, in run
    s_, r, done = self.env.forward_action(mov_mag, rot_mag)
  File "/home/elizabeth/continunous_marvon/environment_ai2thor.py", line 90, in forward_action
    self.run()
  File "continuous_A3C.py", line 113, in run
    self.controller.step(dict(action='MoveAhead', moveMagnitude=move_mag, snapToGrid=False))
    s_, r, done = self.env.forward_action(mov_mag, rot_mag)
  File "/usr/local/lib/python2.7/dist-packages/ai2thor/controller.py", line 537, in step
  File "/home/elizabeth/continunous_marvon/environment_ai2thor.py", line 90, in forward_action
    self.controller.step(dict(action='MoveAhead', moveMagnitude=move_mag, snapToGrid=False))
  File "/usr/local/lib/python2.7/dist-packages/ai2thor/controller.py", line 537, in step
    self.last_event = queue_get(self.request_queue)
  File "/usr/local/lib/python2.7/dist-packages/ai2thor/server.py", line 39, in queue_get
    self.last_event = queue_get(self.request_queue)
  File "/usr/local/lib/python2.7/dist-packages/ai2thor/server.py", line 39, in queue_get
    res = que.get(block=True, timeout=0.5)
  File "/usr/lib/python2.7/Queue.py", line 177, in get
    res = que.get(block=True, timeout=0.5)
  File "/usr/lib/python2.7/Queue.py", line 177, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    self.not_empty.wait(remaining)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
    _sleep(delay)
KeyboardInterrupt

Did you meet this before?
Is this _res = que.get(block=True, timeout=0.5)_ the reason why it stucked?
Do you have any idea to solve this?
Look forward to your reply. Thanks a lot!

**Comment by MorvanZhou** [comment]
This may be a compatibility issue, please comment out the lines related to multiprocessing queue.
